### ISSUE TITLE
Feature Request: Support for Unicode subscripts

### ISSUE THREAD

**Issue by jonesmartins** [tlaplus-community/tlaplus-unicode-converter#13]
## The gist

Translate some string `>>_<something>`, `]_<something>`, `WF_<something>` and `SF_<something>` such that `_<something>` becomes a subscript text. For example,

```tlaplus
Spec == Init /\ [][Next]_vars
```
would be translated as 
```tlaplus
Spec ≜ Init ∧ □[Next]ᵥₐᵣₛ
```

## Caveats

Current Unicode support for subscripts is quite limited: 
- full support for number subscripts;
- some support for lower-case Latin letter subscripts;
- no support for upper-case Latin letter subscripts;
- no support for left- and right-angle brackets; 

Since the Unicode Standard has been slowly adding letter and symbol subscripts, this issue won't be resolved in the short term.

Of course, there'd be no subscripts for subscripts.

## Note

May I also write another issue regarding full Unicode support, much like [Julia's Unicode support](https://docs.julialang.org/en/v1/manual/unicode-input/)? I understand that full Unicode support may have already been discussed elsewhere, and that it would probably impact SANY even further.

**Comment by ahelwer** [comment]
I considered doing this but it basically looks terrible in monospace font so I don't think it's a good idea.

If you're interested in further expanding the Unicode symbols supported by TLA+ you can open a RFC here and speak about it at one of the monthly community calls: https://github.com/tlaplus/rfcs/issues

It should be said that a fair amount of talk about Unicode TLA+ has already been done in these calls (provoked by me) so people might be getting tired of it, and the general consensus in past discussions is that we don't want to overdo it with Unicode symbol support. But it's always good to get more people involved in the process and interested in the issues!

**Comment by jonesmartins** [comment]
> I considered doing this but it basically looks terrible in monospace font so I don't think it's a good idea.

The current subscript support makes them look even worse, so I'll wait for further Unicode subscript support before I propose an official RFC.

> It should be said that a fair amount of talk about Unicode TLA+ has already been done in these calls (provoked by me) so people might be getting tired of it, and the general consensus in past discussions is that we don't want to overdo it with Unicode symbol support.

Thanks for the heads-up! I think Unicode support is quite relevant.
It's hard for me to attend these calls with my current schedule. They aren't recorded anymore, so I can't watch them either.
