### ISSUE TITLE
tlauc wipes the file if there is invalid syntax

### ISSUE THREAD

**Issue by bugarela** [tlaplus-community/tlaplus-unicode-converter#14]
I had a syntax issue on my file, and when running `tlauc`, all the contents of said file were erased :grimacing: 

```
$ cat test.tla
------ MODULE test ----
foo == invalid,
=======================
$ tlauc test.tla
Error: Failed to correctly parse input TLA⁺ file; use --force flag to bypass this check.
Syntax errors might occur on or near the following lines: [2].
$ cat test.tla
$
```

**Comment by ahelwer** [comment]
Woaoaaaah yes this is very bad!!!

**Comment by ahelwer** [comment]
Easy fix but very embarrassing! Thanks for the report. Will cut a release shortly. Bug was introduced in #10.

**Comment by bugarela** [comment]
Luckily I found it in a 10-line file that I could easily rewrite, so don't worry about it! Hopefully you fixed it before anyone suffered from it.
