### ISSUE TITLE
Diamond operator tiny in VSCode on macOS

### ISSUE THREAD

**Issue by lemmy** [tlaplus-community/tlaplus-unicode-converter#4]
macos 13.3.1
vscode 1.78.2

<img width="437" alt="Screenshot 2023-05-15 at 12 52 35 PM" src="https://github.com/tlaplus-community/tlauc/assets/88777/205ead7c-8cb6-47e2-aafc-b8eb6800bb90">

**Comment by ahelwer** [comment]
This will depend on the font used I think. However, perhaps a different unicode diamond (there are many) would have a larger presentation in more fonts.

**Comment by ahelwer** [comment]
Closing in favor of https://github.com/tlaplus/rfcs/issues/22
