### ISSUE TITLE
Feature request: fmt

### ISSUE THREAD

**Issue by gterzian** [tlaplus-community/tlaplus-unicode-converter#5]
The pain point for me is not so much the ASCII, I've gotten used to it, it's rather the manual formatting. Any plans to add  a feature like `rustfmt`? 

Thank you for your consideration.

**Comment by ahelwer** [comment]
If someone else wants to write it they're welcome to but it isn't in my planned projects for the next several years. @craft095 is apparently working on some kind of style checking tool.
