### ISSUE TITLE
--output needed despite --overwrite

### ISSUE THREAD

**Issue by lemmy** [tlaplus-community/tlaplus-unicode-converter#9]
Why do I have to pass `--output` with `-overwrite`?  Currently, `--overwrite` seems to be a no-op with `tlauc --input foo.tla --output bar.tla --overwrite`?

**Comment by ahelwer** [comment]
The `--overwrite` flag just tells TLAUC to overwrite a file if `--output` already exists. The CLI design is a bit janky & verbose although I erred on the side of making it hard to accidentally overwrite files.

**Comment by ahelwer** [comment]
@lemmy what do you think, should the CLI be more terse and ask for fewer flags before overwriting things? In the simplest case, should `tlauc ModuleName.tla` do something like convert the file in-place from unicode to ascii (or vice versa)?

**Comment by lemmy** [comment]
I'd suggest to remove the `--overwrite` safeguard and simply replace the content of `bar` in `tlauc --input bar.tla --output bar.tla`.
